title = "IRL Podcast: Online Life is Real Life"
email = "irlpodcast@mozilla.com"
baseURL = "https://irlpodcast.org"
googleAnalytics = "GTM-5H9T7GF"

[params]
    description = "Veronica Belmont explores real stories of life online – and real talk about how we can all keep the Internet healthy, weird and wonderful. IRL is an original podcast from Mozilla."